export const ApiErrors = {
  UNAUTHORIZED: 'Unauthorized',
  SESSION_STALE: 'session_stale',
  NOT_FOUND: 'Not found',
  SLUG_TAKEN: 'slug_taken',
  SITE_NAME_EXISTS: 'Site name already exists.',
  EMAIL_IN_USE: 'Email already in use.',
  EMAIL_NOT_SUPPORTED: 'Only Gmail addresses are supported.',
  FIELDS_REQUIRED: 'All fields are required.',
  QUOTA_EXCEEDED: 'quota_exceeded',
  LIMIT_EXCEEDED: 'limit_exceeded',
  INVALID_DOMAIN: 'invalid_domain',
  DOMAIN_TAKEN: 'domain_taken',
  VERCEL_API_ERROR: 'vercel_api_error',
  VALIDATION_FAILED: 'validation_failed',
  DOMAIN_REQUIRED: 'domain_required',
  DOMAIN_NOT_VERIFIED: 'domain_not_verified',
  BAD_REQUEST: 'bad_request',
  AI_QUOTA_EXHAUSTED: 'ai_quota_exhausted',
  AI_GENERATION_FAILED: 'ai_generation_failed',
} as const;
